# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{redhillonrails_core}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["RedHill Consulting, Pty. Ltd.", "Christian Eager"]
  s.date = %q{2009-08-25}
  s.description = %q{RedHill on Rails Core is a plugin that features to support other RedHill on Rails plugins. Those features include:
        * Creating and dropping views;
        * Creating and removing foreign-keys;
        * Obtaining indexes directly from a model class; and
        * Determining when Schema.define() is running.
    }
  s.email = %q{christian@perpenduum.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/red_hill_consulting/core/active_record/base.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/abstract_adapter.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/column.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/foreign_key_definition.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/index_definition.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/mysql4_adapter.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/mysql5_adapter.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/mysql_adapter.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/mysql_column.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/postgresql_adapter.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/schema_statements.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/sqlite3_adapter.rb",
     "lib/red_hill_consulting/core/active_record/connection_adapters/table_definition.rb",
     "lib/red_hill_consulting/core/active_record/schema.rb",
     "lib/red_hill_consulting/core/active_record/schema_dumper.rb",
     "lib/redhillonrails_core.rb",
     "spec/models/child.rb",
     "spec/models/top.rb",
     "spec/redhillonrails_core_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helper_module.rb",
     "tasks/db/comments.rake"
  ]
  s.homepage = %q{http://github.com/frolic/redhillonrails_core}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem version of redhillonrails_core}
  s.test_files = [
    "spec/models/child.rb",
     "spec/models/top.rb",
     "spec/redhillonrails_core_spec.rb",
     "spec/spec_helper.rb",
     "spec/spec_helper_module.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end
